# Provision an EC2 instance
template_path: remote/managed-ec2-linux-v1.j2
stack_name: ahayden-testhost-lin
sceptre_user_data:
  Distro: "aws"     # (valid values: aws, ubuntu) AMIId must match distro
  # (Optional) Expose ports to incoming traffic (default is no open ports) (valid range: 1-65535)
  # OpenPorts: ["80","443"]
parameters:
  # The Sage deparment (Platform, CompOnc, SysBio, Governance, etc..)
  Department: "Platform"
  # The Sage project (Infrastructure, amp-ad, ntap, dream, etc..)
  Project: "Infrastructure"
  # The resource owner
  OwnerEmail: "aaron.hayden@sagebase.org"

  # Default account settings, leave alone unless you plan to override
  VpcName: "sandcastlevpc"
  KeyName: "sandbox"
  AMIId: "ami-0b898040803850657"      # AWS linux 2 AMI 2.0.20190618 x86_64 HVM gp2
  # AMIId: "ami-0a313d6098716f372"      # Ubuntu, 18.04 LTS, amd64 bionic image build on 2019-02-12

  # Integration with our jumpcloud directory service (do not change)
  JcConnectKey: !ssm /infra/JcConnectKey
  JcServiceApiKey: !ssm /infra/JcServiceApiKey
  JcSystemsGroupId: !ssm /infra/JcSystemsGroupId

# For CI system (do not change)
hooks:
  before_launch:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/managed-ec2-linux-v1.j2 --create-dirs -o templates/remote/managed-ec2-linux-v1.j2"
  after_create:
    - !ec2_notify "{{stack_group_config.aws_account_name}} {{stack_group_config.aws_account_email}}"
