template_path: remote/managed-ec2.yaml
stack_name: toil-test-machine
parameters:
  # The Sage deparment (Platform, CompOnc, SysBio, Governance, etc..)
  Department: "CompOnc"
  # The Sage project (Infrastructure, amp-ad, ntap, dream, etc..)
  Project: "NF_OSI"
  VolumeSize: "800"
  # The resource owner
  OwnerEmail: "sara.gosline@sagebase.org"

  VpcName: {{stack_group_config.default_vpc}}
  KeyName: {{stack_group_config.default_key_pair}}
  AMIId: {{stack_group_config.default_ami}}

  InstanceType: "m4.4xlarge"
  JcConnectKey: !ssm /infra/JcConnectKey
  JcServiceApiKey: !ssm /infra/JcServiceApiKey
  JcSystemsGroupId: !ssm /infra/JcSystemsGroupId
hooks:
  before_create:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/managed-ec2-v8.yaml --create-dirs -o templates/remote/managed-ec2.yaml"
  before_update:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/managed-ec2-v8.yaml --create-dirs -o templates/remote/managed-ec2.yaml"
  after_create:
    - !ec2_notify "{{stack_group_config.aws_account_name}} {{stack_group_config.aws_account_email}}"
