template_path: remote/managed-ec2-v10.j2
stack_name: tom-analysis
parameters:
  Department: "CompOnc"
  Project: "ntap"
  OwnerEmail: "thomas.yu@sagebase.org"
  VpcName: "sandcastlevpc"
  KeyName: "sandbox"
  AMIId: "ami-0de53d8956e8dcf80"
  InstanceType: "t2.xlarge"
  VolumeSize: "50"
  JcConnectKey: !ssm /infra/JcConnectKey
  JcServiceApiKey: !ssm /infra/JcServiceApiKey
  JcSystemsGroupId: !ssm /infra/JcSystemsGroupId
hooks:
  before_create:
    - !cmd curl "https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/managed-ec2-v10.j2 --create-dirs -o templates/remote/managed-ec2-v10.j2"
  before_update:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/managed-ec2-v10.j2 --create-dirs -o templates/remote/managed-ec2-v10.j2"
  after_create:
    - !ec2_notify "{{stack_group_config.aws_account_name}} {{stack_group_config.aws_account_email}}"

