# Provision a Windows EC2 instance
template_path: remote/managed-ec2-win-v1.yaml
stack_name: xschildw-test-stack-tags
parameters:
  # Default account settings, leave alone unless you plan to override
  VpcName: "{{stack_group_config.default_vpc}}"
  KeyName: "{{stack_group_config.default_key_pair}}"
  AMIId: "{{stack_group_config.default_win_ami}}"

  # Settings have default values but can be overriden. Set the below
  # parameters *only* if you want to override the defaults.

  # (Optional) EC2 instance type, default is "t2.small" (other available types https://aws.amazon.com/ec2/instance-types/)
  #  InstanceType: "t2.medium"
  # (Optional) EC2 boot volume size in GB, default is 30GB, Max is 1000GB
  # VolumeSize: "50"
  # (Optional) ID of the base AMI (default: "ami-02d43577e47e684d9" Windows_Server-2019-English-Base-Non-EBS-Encrypted)
  #  AMIId: "ami-02d43577e47e684d9"      # Windows_Server-2019-English-Full-ContainersLatest-2019.03.13
  # (Optional) Run EC2 in a subnet (default: PrivateSubnet) (valid values: PrivateSubnet or PublicSubnet)
  # VpcSubnet: "PublicSubnet"
  # (Optional) Expose a port to incoming traffic (default is no open ports) (valid range: 1-65535)
  # OpenPort: "80"
  # (Optional) Set true to enable daily backups (default: false)
  # BackupEc2: "true"
  # (Optional) Number of daily backups to keep (default: 7) (valid range: 1-180)
  # SnapshotCount: "14"

  # Integration with our jumpcloud directory service (do not change)
  JcConnectKey: !ssm /infra/JcConnectKey
  JcServiceApiKey: !ssm /infra/JcServiceApiKey
  JcSystemsGroupId: !ssm /infra/JcSystemsGroupId

stack-tags:
  Department: "Platform-st"
  Project: "Infrastructure-st"
  OwnerEmail: "x.schildwachter@sagebase.org"

# For CI system (do not change)
hooks:
  before_create:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/managed-ec2-win-v1.yaml --create-dirs -o templates/remote/managed-ec2-win-v1.yaml"
  before_update:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/managed-ec2-win-v1.yaml --create-dirs -o templates/remote/managed-ec2-win-v1.yaml"
  after_create:
    - !ec2_notify "{{stack_group_config.aws_account_name}} {{stack_group_config.aws_account_email}}"
